name: Lighthouse Report Generation Test

on:
  push:
    branches:
      - lighthouse-test

jobs:
  lighthouse:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: 'Installing deps'
        run: |
          yarn
          npm i -g @lhci/cli@0.9.x

      - name: 'Run'
        run: yarn start &

      - name: 'Run Lighthouse tests'
        continue-on-error: true
        run: lhci autorun --config=lighthouse-instruction.json

      - name: 'Upload report'
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: lhci-reports
          path: |
            ./lighthouseci/
          # if-no-files-found: error
          # if: ${{ success() && steps.lighthouse.outputs.hasHtmlReport == 'true' && steps.lighthouse.outputs.hasJsonReport == 'true' }}
