name: Lighthouse Report Generation Test

on:
  push:
    branches:
      - lighthouse-test

jobs:
  lighthouse:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: 'Installing deps'
        run: |
          yarn
          npm i -g @lhci/cli@0.9.x

      - name: 'Run'
        run: yarn start &

#      - name: 'Wait ...'
#        run: npx wait-on http://localhost:3000/react-pipeline/

      - name: 'Run Lighthouse tests'
        run: lhci autorun --config=lighthouse-instruction.json
